const express = require("express");
const authController = require("../controllers/auth.controller");
const whatsappController = require("../controllers/whatsapp.controller");
const messagingController = require("../controllers/messaging.controller");
const agendaController = require("../controllers/agenda.controller");
const chatController = require("../controllers/chat.controller");
const agentController = require("../controllers/agent.controller");
const modelController = require("../controllers/model.controller");
const taskController = require("../controllers/task.controller");
const fileController = require("../controllers/file.controller");
const integrationController = require("../controllers/integration.controller");
const mobileController = require("../controllers/mobile.controller");
const internalChatGroupsController = require("../controllers/internal-chat-groups.controller");
const authService = require("../modules/auth/auth.service");
const mobileAuthMiddleware = require("../modules/mobile/mobile-auth-middleware");

const router = express.Router();

router.get("/login", authController.renderLoginPage);
router.post("/login", authController.login);
router.post("/api/mobile/login", mobileController.login);
router.get("/register", authService.ensureRegistrationAllowed, authController.renderRegisterPage);
router.post("/register", authService.ensureRegistrationAllowed, authController.register);
router.post("/logout", authController.logout);

router.use("/api/mobile", mobileAuthMiddleware.ensureMobileAuthenticated);
router.post("/api/mobile/logout", mobileController.logout);
router.get("/api/mobile/me", mobileController.getMe);
router.get("/api/mobile/conversations", mobileController.listConversations);
router.get("/api/mobile/conversations/:conversationId/messages", mobileController.getConversationMessages);
router.post("/api/mobile/conversations/:conversationId/messages", mobileController.sendConversationMessage);
router.delete("/api/mobile/conversations/:conversationId/messages/:messageId", mobileController.deleteConversationMessage);
router.post("/api/mobile/conversations/:conversationId/messages/:messageId/delete", mobileController.deleteConversationMessage);
router.post("/api/mobile/conversations/:conversationId/read", mobileController.markConversationRead);
router.delete("/api/mobile/conversations/:conversationId", mobileController.deleteConversation);
router.post("/api/mobile/conversations/:conversationId/delete", mobileController.deleteConversation);
router.post("/api/mobile/devices", mobileController.registerDevice);
router.delete("/api/mobile/devices/:token", mobileController.deleteDevice);

router.use(authService.ensureAuthenticated);

router.get("/", messagingController.renderMessagingPage);
router.get("/whatsapp", messagingController.renderMessagingPage);
router.get("/mensajeria", messagingController.renderMessagingPage);
router.get('/usuarios/nuevo', authService.ensureRegistrationAllowed, authController.renderRegisterPage);
router.post('/usuarios/:userId/actualizar', authController.updateUser);
router.post('/usuarios/:userId/eliminar', authController.deleteUser);
router.get("/grupos-internos", internalChatGroupsController.renderGroupsPage);
router.get("/agenda", agendaController.renderAgendaPage);
router.get("/chat", chatController.renderChatPage);
router.get("/agente/nuevo", agentController.renderNewAgentPage);
router.get("/agente/roles", agentController.renderRolesPage);
router.get("/modelos", modelController.renderModelsPage);
router.get("/integraciones", integrationController.renderIntegrationsPage);
router.get("/tareas/nueva", taskController.renderNewTaskPage);
router.get("/archivos/gestionar", fileController.renderManageFilesPage);

router.get("/api/whatsapp/status", whatsappController.getStatus);
router.get("/api/whatsapp/groups", whatsappController.listGroups);
router.post("/api/whatsapp/qr/refresh", whatsappController.refreshQr);
router.get("/api/messaging/status", messagingController.getStatus);
router.get("/api/messaging/groups", messagingController.listGroups);
router.post("/api/messaging/channel", messagingController.updateActiveChannel);
router.post("/api/messaging/telegram/config", messagingController.updateTelegramConfig);
router.post("/api/messaging/internal-chat/config", messagingController.updateInternalChatConfig);
router.post("/api/messaging/refresh", messagingController.refreshProvider);
router.get("/api/contacts", agendaController.listContacts);
router.post("/api/contacts", agendaController.createContact);
router.put("/api/contacts/:contactId", agendaController.updateContact);
router.delete("/api/contacts/:contactId", agendaController.deleteContact);
router.get("/api/chat/:contactId/messages", chatController.getConversation);
router.post("/api/chat/send", chatController.sendMessage);
router.post("/api/chat/clear", chatController.clearConversation);
router.get("/api/chat/:contactId/clear", chatController.clearConversation);
router.post("/api/chat/:contactId/clear", chatController.clearConversation);
router.delete("/api/chat/:contactId/clear", chatController.clearConversation);
router.get("/api/roles", agentController.listRoles);
router.post("/api/roles", agentController.createRole);
router.put("/api/roles/:roleId", agentController.updateRole);
router.delete("/api/roles/:roleId", agentController.deleteRole);
router.post("/api/agents", agentController.createAgent);
router.put("/api/agents/:agentId", agentController.updateAgent);
router.delete("/api/agents/:agentId", agentController.deleteAgent);
router.post("/api/models", modelController.createModel);
router.put("/api/models/:modelId", modelController.updateModel);
router.delete("/api/models/:modelId", modelController.deleteModel);
router.post("/api/models/:modelId/test", modelController.testModel);
router.get("/api/integrations", integrationController.listIntegrations);
router.post("/api/integrations", integrationController.createIntegration);
router.put("/api/integrations/:integrationId", integrationController.updateIntegration);
router.delete("/api/integrations/:integrationId", integrationController.deleteIntegration);
router.post("/api/tasks", taskController.createTask);
router.get("/api/tasks/:taskId/prompt", taskController.getTaskPrompt);
router.get("/api/tasks/:taskId", taskController.getTaskDetails);
router.put("/api/tasks/:taskId", taskController.updateTask);
router.delete("/api/tasks/:taskId", taskController.deleteTask);
router.post("/api/tasks/:taskId/queue", taskController.queueTask);
router.post("/api/tasks/:taskId/execute", taskController.executeTask);
router.post("/api/tasks/:taskId/logs/clear", taskController.clearTaskLogs);
router.get("/api/files", fileController.listFiles);
router.post("/api/files/upload", fileController.uploadFile);
router.delete("/api/files/:fileId", fileController.deleteFile);
router.get("/api/internal-chat/groups", internalChatGroupsController.listGroups);
router.post("/api/internal-chat/groups", internalChatGroupsController.createGroup);
router.put("/api/internal-chat/groups/:groupId", internalChatGroupsController.updateGroup);
router.delete("/api/internal-chat/groups/:groupId", internalChatGroupsController.deleteGroup);

module.exports = router;


